version: '3.5'
services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass redistest
    container_name: redis_archetype_test
    ports:
      - "6379:6379"
  
  dbMongo:
    image: mongo:5.0.0
    restart: always
    container_name: mongo_archetype_mstest
    ports:
      - 27020:27017
    environment:
      MONGODB_DATABASE: mydatabase
      MONGO_INITDB_ROOT_USERNAME: cbdiegox    # Usuario root
      MONGO_INITDB_ROOT_PASSWORD: password123 # Contrase√±a root
    volumes:
      - ./mongo:/data/db
